"""fix attributes

Revision ID: 2e28ea3e8883
Revises: 834ab8a70342
Create Date: 2021-03-13 18:10:06.047229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e28ea3e8883'
down_revision = '834ab8a70342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'datetime_add',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    op.alter_column('post', 'id_user',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('post', 'message',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'post', ['title'])
    op.alter_column('user', 'datetime_reg',
               existing_type=mysql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'datetime_reg',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'post', type_='unique')
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('post', 'message',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('post', 'id_user',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('post', 'datetime_add',
               existing_type=mysql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
