"""change datetime

Revision ID: 9cd08651c8d5
Revises: 9eab097deef5
Create Date: 2021-03-13 18:58:09.147244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cd08651c8d5'
down_revision = '9eab097deef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_datetime_add'), 'post', ['datetime_add'], unique=False)
    op.create_index(op.f('ix_user_datetime_reg'), 'user', ['datetime_reg'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_datetime_reg'), table_name='user')
    op.drop_index(op.f('ix_post_datetime_add'), table_name='post')
    # ### end Alembic commands ###
