"""add followers table

Revision ID: e63377fe7284
Revises: fa316ee48268
Create Date: 2021-03-18 19:03:47.691584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63377fe7284'
down_revision = 'fa316ee48268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_follower', sa.Integer(), nullable=True),
    sa.Column('id_followed', sa.Integer(), nullable=True),
    sa.Column('datetime_add', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_followed'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_follower'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
