"""add new items in users table

Revision ID: fa316ee48268
Revises: e799807ae8d8
Create Date: 2021-03-18 11:46:30.024650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa316ee48268'
down_revision = 'e799807ae8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('datetime_last', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_datetime_last'), 'user', ['datetime_last'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_datetime_last'), table_name='user')
    op.drop_column('user', 'datetime_last')
    # ### end Alembic commands ###
